---

- hosts: localhost
  tasks:
    - name: install packages for ansible support
      raw: dnf -y -e0 -d0 install python-dnf libselinux-python
      when: ansible_distribution == "Fedora"

- hosts: localhost
  tasks:
    - name: install boto module for ansible ec2.py
      pip:
        name: boto

